export const RACES_DATA_2027 = {
  "Pre-Season Testing": {
    round: "T",
    raceKey: "f1.races.testing",
    circuitKey: "f1.circuits.sakhir",
    date: "2027-02-27",
    city: "Sakhir, BH",
    country: "Bahrain",
    lat: 26.0325,
    lng: 50.5106,
    displayName: "Sakhir",
    flag: "bh.webp",
  },
  "Bahrain Grand Prix": {
    round: 1,
    raceKey: "f1.races.bahrain",
    circuitKey: "f1.circuits.sakhir",
    date: "2027-03-14",
    city: "Sakhir, BH",
    country: "Bahrain",
    lat: 26.0325,
    lng: 50.5106,
    displayName: "Sakhir",
    flag: "bh.webp",
  },
  "Saudi Arabian Grand Prix": {
    round: 2,
    raceKey: "f1.races.saudi_arabia",
    circuitKey: "f1.circuits.jeddah",
    date: "2027-03-21",
    city: "Jeddah, SA",
    country: "Saudi Arabia",
    lat: 21.6319,
    lng: 39.1044,
    displayName: "Jeddah",
    flag: "sa.webp",
  },
  "Australian Grand Prix": {
    round: 3,
    raceKey: "f1.races.australia",
    circuitKey: "f1.circuits.albert_park",
    date: "2027-04-04",
    city: "Melbourne, AU",
    country: "Australia",
    lat: -37.8497,
    lng: 144.968,
    displayName: "Melbourne",
    flag: "au.webp",
  },
  "Japanese Grand Prix": {
    round: 4,
    raceKey: "f1.races.japan",
    circuitKey: "f1.circuits.suzuka",
    date: "2027-04-11",
    city: "Suzuka, JP",
    country: "Japan",
    lat: 34.8431,
    lng: 136.5407,
    displayName: "Suzuka",
    flag: "jp.webp",
  },
  "Chinese Grand Prix": {
    round: 5,
    raceKey: "f1.races.china",
    circuitKey: "f1.circuits.shanghai",
    date: "2027-04-18",
    city: "Shanghai, CN",
    country: "China",
    lat: 31.3389,
    lng: 121.2197,
    displayName: "Shanghai",
    flag: "cn.webp",
  },
  "Miami Grand Prix": {
    round: 6,
    raceKey: "f1.races.miami",
    circuitKey: "f1.circuits.miami",
    date: "2027-05-02",
    city: "Miami, US",
    country: "USA",
    lat: 25.9581,
    lng: -80.2389,
    displayName: "Miami",
    flag: "us.webp",
  },
  "Canadian Grand Prix": {
    round: 7,
    raceKey: "f1.races.canada",
    circuitKey: "f1.circuits.montreal",
    date: "2027-05-23",
    city: "Montreal, CA",
    country: "Canada",
    lat: 45.5000,
    lng: -73.5228,
    displayName: "Montreal",
    flag: "ca.webp",
  },
  "Monaco Grand Prix": {
    round: 8,
    raceKey: "f1.races.monaco",
    circuitKey: "f1.circuits.monaco",
    date: "2027-06-06",
    city: "Monte Carlo, MC",
    country: "Monaco",
    lat: 43.7347,
    lng: 7.4206,
    displayName: "Monte Carlo",
    flag: "mc.webp",
  },
  "Portuguese Grand Prix": {
    round: 9,
    raceKey: "f1.races.portugal",
    circuitKey: "f1.circuits.portimao",
    date: "2027-06-20",
    city: "Portimão, PT",
    country: "Portugal",
    lat: 37.227,
    lng: -8.626,
    displayName: "Portimão",
    flag: "pt.webp",
  },
  "British Grand Prix": {
    round: 10,
    raceKey: "f1.races.great_britain",
    circuitKey: "f1.circuits.silverstone",
    date: "2027-07-04",
    city: "Silverstone, GB",
    country: "United Kingdom",
    lat: 52.0786,
    lng: -1.0169,
    displayName: "Silverstone",
    flag: "gb.webp",
  },
  "Austrian Grand Prix": {
    round: 11,
    raceKey: "f1.races.austria",
    circuitKey: "f1.circuits.spielberg",
    date: "2027-07-11",
    city: "Spielberg, AT",
    country: "Austria",
    lat: 47.2197,
    lng: 14.7647,
    displayName: "Spielberg",
    flag: "at.webp",
  },
  "Belgian Grand Prix": {
    round: 12,
    raceKey: "f1.races.belgium",
    circuitKey: "f1.circuits.spa",
    date: "2027-07-25",
    city: "Stavelot, BE",
    country: "Belgium",
    lat: 50.4372,
    lng: 5.9714,
    displayName: "Spa-Francorchamps",
    flag: "be.webp",
  },
  "Hungarian Grand Prix": {
    round: 13,
    raceKey: "f1.races.hungary",
    circuitKey: "f1.circuits.hungaroring",
    date: "2027-08-01",
    city: "Mogyoród, HU",
    country: "Hungary",
    lat: 47.5800,
    lng: 19.2486,
    displayName: "Hungaroring",
    flag: "hu.webp",
  },
  "Italian Grand Prix": {
    round: 14,
    raceKey: "f1.races.italy",
    circuitKey: "f1.circuits.monza",
    date: "2027-09-05",
    city: "Monza, IT",
    country: "Italy",
    lat: 45.6156,
    lng: 9.2811,
    displayName: "Monza",
    flag: "it.webp",
  },
  "Spanish Grand Prix": {
    round: 15,
    raceKey: "f1.races.spain",
    circuitKey: "f1.circuits.madrid",
    date: "2027-09-12",
    city: "Madrid, ES",
    country: "Spain",
    lat: 40.4667,
    lng: -3.6167,
    displayName: "Madrid",
    flag: "es.webp",
  },
  "Azerbaijan Grand Prix": {
    round: 16,
    raceKey: "f1.races.azerbaijan",
    circuitKey: "f1.circuits.baku",
    date: "2027-09-26",
    city: "Baku, AZ",
    country: "Azerbaijan",
    lat: 40.3725,
    lng: 49.8533,
    displayName: "Baku",
    flag: "az.webp",
  },
  "Turkish Grand Prix": {
    round: 17,
    raceKey: "f1.races.turkey",
    circuitKey: "f1.circuits.istanbul",
    date: "2027-10-03",
    city: "Istanbul, TR",
    country: "Turkey",
    lat: 40.9517,
    lng: 29.4050,
    displayName: "Istanbul",
    flag: "tr.webp",
  },
  "Singapore Grand Prix": {
    round: 18,
    raceKey: "f1.races.singapore",
    circuitKey: "f1.circuits.marina_bay",
    date: "2027-10-10",
    city: "Singapore, SG",
    country: "Singapore",
    lat: 1.2914,
    lng: 103.864,
    displayName: "Marina Bay",
    flag: "sg.webp",
  },
  "United States Grand Prix": {
    round: 19,
    raceKey: "f1.races.usa",
    circuitKey: "f1.circuits.cota",
    date: "2027-10-24",
    city: "Austin, US",
    country: "USA",
    lat: 30.1328,
    lng: -97.6411,
    displayName: "Austin",
    flag: "us.webp",
  },
  "Mexico City Grand Prix": {
    round: 20,
    raceKey: "f1.races.mexico",
    circuitKey: "f1.circuits.hermanos_rodriguez",
    date: "2027-10-31",
    city: "Mexico City, MX",
    country: "Mexico",
    lat: 19.4042,
    lng: -99.0907,
    displayName: "Mexico City",
    flag: "mx.webp",
  },
  "Brazilian Grand Prix": {
    round: 21,
    raceKey: "f1.races.brazil",
    circuitKey: "f1.circuits.interlagos",
    date: "2027-11-07",
    city: "São Paulo, BR",
    country: "Brazil",
    lat: -23.7036,
    lng: -46.6997,
    displayName: "São Paulo",
    flag: "br.webp",
  },
  "Las Vegas Grand Prix": {
    round: 22,
    raceKey: "f1.races.las_vegas",
    circuitKey: "f1.circuits.las_vegas",
    date: "2027-11-20",
    city: "Las Vegas, US",
    country: "USA",
    lat: 36.1147,
    lng: -115.1728,
    displayName: "Las Vegas",
    flag: "us.webp",
  },
  "Qatar Grand Prix": {
    round: 23,
    raceKey: "f1.races.qatar",
    circuitKey: "f1.circuits.lusail",
    date: "2027-12-05",
    city: "Lusail, QA",
    country: "Qatar",
    lat: 25.4900,
    lng: 51.4542,
    displayName: "Lusail",
    flag: "qa.webp",
  },
  "Abu Dhabi Grand Prix": {
    round: 24,
    raceKey: "f1.races.abu_dhabi",
    circuitKey: "f1.circuits.yas_marina",
    date: "2027-12-12",
    city: "Abu Dhabi, AE",
    country: "UAE",
    lat: 24.4672,
    lng: 54.6031,
    displayName: "Yas Marina",
    flag: "ae.webp",
  }
};
