export const locationMaps = {
    melbourne: "albert_park",
    australia: "albert_park",
    austin: "americas",
    usa: "americas",
    bahrain: "bahrain",
    sakhir: "bahrain",
    baku: "baku",
    azerbaijan: "baku",
    budapest: "hungaroring",
    hungary: "hungaroring",
    imola: "imola",
    "emilia romagna": "imola",
    "são paulo": "interlagos",
    "sao paulo": "interlagos",
    brazil: "interlagos",
    jeddah: "jeddah",
    "saudi arabia": "jeddah",
    "marina bay": "marina_bay",
    singapore: "marina_bay",
    monaco: "monaco",
    "monte carlo": "monaco",
    spielberg: "red_bull_ring",
    austria: "red_bull_ring",
    "mexico city": "rodriguez",
    mexico: "rodriguez",
    shanghai: "shanghai",
    china: "shanghai",
    silverstone: "silverstone",
    uk: "silverstone",
    britain: "silverstone",
    "spa-francorchamps": "spa",
    spa: "spa",
    belgium: "spa",
    suzuka: "suzuka",
    japan: "suzuka",
    "las vegas": "vegas",
    vegas: "vegas",
    montréal: "villeneuve",
    montreal: "villeneuve",
    canada: "villeneuve",
    zandvoort: "zandvoort",
    netherlands: "zandvoort",
    miami: "miami",
    "miami gardens": "miami",
    monza: "monza",
    italy: "monza",
    barcelona: "catalunya",
    spain: "catalunya",
    lusail: "losail",
    qatar: "losail",
    "yas island": "yas_marina",
    "yas marina": "yas_marina",
    "abu dhabi": "yas_marina",
};
