export const locationMaps = {
    melbourne: "albert_park",
    australia: "albert_park",
    albert_park: "albert_park",
    austin: "cota",
    usa: "cota",
    cota: "cota",
    americas: "cota",
    bahrain: "bahrain",
    sakhir: "bahrain",
    baku: "baku",
    azerbaijan: "baku",
    budapest: "hungaroring",
    hungary: "hungaroring",
    hungaroring: "hungaroring",
    "mogyoród": "hungaroring",
    "mogyorod": "hungaroring",
    imola: "imola",
    "emilia romagna": "imola",
    "são paulo": "interlagos",
    "sao paulo": "interlagos",
    brazil: "interlagos",
    interlagos: "interlagos",
    jeddah: "jeddah",
    "saudi arabia": "jeddah",
    "marina bay": "marina_bay",
    singapore: "marina_bay",
    marina_bay: "marina_bay",
    monaco: "monaco",
    "monte carlo": "monaco",
    monte_carlo: "monaco",
    spielberg: "red_bull_ring",
    austria: "red_bull_ring",
    red_bull_ring: "red_bull_ring",
    "mexico city": "rodriguez",
    mexico: "rodriguez",
    rodriguez: "rodriguez",
    hermanos_rodriguez: "rodriguez",
    shanghai: "shanghai",
    china: "shanghai",
    silverstone: "silverstone",
    uk: "silverstone",
    britain: "silverstone",
    "spa-francorchamps": "spa",
    stavelot: "spa",
    spa: "spa",
    belgium: "spa",
    suzuka: "suzuka",
    japan: "suzuka",
    "las vegas": "vegas",
    vegas: "vegas",
    vegas_strip: "vegas",
    montréal: "villeneuve",
    montreal: "villeneuve",
    canada: "villeneuve",
    villeneuve: "villeneuve",
    gilles_villeneuve: "villeneuve",
    zandvoort: "zandvoort",
    netherlands: "zandvoort",
    miami: "miami",
    "miami gardens": "miami",
    monza: "monza",
    italy: "monza",
    barcelona: "catalunya",
    spain: "catalunya",
    catalunya: "catalunya",
    lusail: "losail",
    qatar: "losail",
    losail: "losail",
    "yas island": "yas_marina",
    "yas marina": "yas_marina",
    "abu dhabi": "yas_marina",
    yas_marina: "yas_marina",
    "kuala lumpur": "sepang",
    "malaysia": "sepang",
    "sepang": "sepang",
    "madrid": "madrid",
    "madring": "madrid",
    "portugal": "portimao",
    "portimão": "portimao",
    "portimao": "portimao",
    "turkey": "istanbul",
    "istanbul": "istanbul"
};
